
use musicas;

create table tb_artistas(
    id_artistas int primary key auto_increment,
    nm_artistas varchar(100) not null
);

create table tb_albuns(
    id_albuns int primary key auto_increment,
    nm_albuns varchar(100) not null,
    dt_lancamento year,
    id_artistas int,
    foreign key (id_artistas) references tb_artistas(id_artistas)
);

create table tb_musica(
    id_musicas int primary key auto_increment,
    nm_musicas varchar(100) not null,
    id_albuns int,
    foreign key (id_albuns) references tb_albuns(id_albuns)
);




insert into tb_artistas(id_artistas, nm_artistas)  values
(1,'BK'),
(2,'Playboi Carti'),
(3,'Travis Scott'),
(4, 'vmz'),
(5, '7MZ'),
(6,'anirap'),
(7,'mc ig'),
(8,'veigh'),
(9,'lady gaga'),
(10,'ludmilla'),
(11,'anitta'),
(12,'chitaozinho e xororo'),
(13,'ariana grande'),
(14,'mc negao original'),
(15,'daniel caesar');

INSERT INTO tb_albuns(id_albuns, nm_albuns, dt_lancamento) VALUES
(1, 'Icarus', '2022'),
(1, 'Diamantes, Lágrimas e Rosto para Esquecer', '2025'),
(1, 'Castelo e Ruínas', '2016'),
(2, 'Music', '2025'),
(2, 'Whole Lotta Red', '2020'),
(2, 'Die Lit', '2018'),
(3, 'Astroworld', '2018'),
(3, 'Rodeo', '2015'),
(3, 'JackBoys', '2019'),
(4, 'Planetas', '2020'),
(4, 'Tributos', '2018'),
(4, 'Liberdade', '2023'),
(5, 'Agente Zero', '2022'),
(5, 'Jinchuuriki', '2020'),
(5, '7Minutoz', '2024'),
(6, 'Blue Lock', '2024'),
(6, 'Dragon Ball', '2023'),
(6, 'Ataque dos Vilões', '2025'),
(7, 'Feliz no Simples', '2025'),
(7, 'Todo Mundo Odeia o IG', '2024'),
(7, 'Ninguém Tá Puro!', '2023'),
(8, 'Eu Venci o Mundo', '2025'),
(8, 'Dos Prédios Deluxe', '2023'),
(8, 'Meu Nome é VGH', '2024'),
(9, 'The Fame', '2008'),
(9, 'Born This Way', '2011'),
(9, 'Chromatica', '2020'),
(10, 'Hoje', '2014'),
(10, 'A Danada Sou Eu', '2016'),
(10, 'Numanice', '2021'),
(12, 'Evidências', '1990'),
(12, 'Cowboy do Asfalto', '1991'),
(12, 'Tom do Sertão', '2015'),
(13, 'Yours Truly', '2013'),
(13, 'Dangerous Woman', '2016'),
(13, 'Sweetener', '2018'),
(14, 'Originalidade', '2020'),
(14, 'Funk do Gueto', '2021'),
(14, 'Poder do Grave', '2023'),
(15, 'Freudian', '2017'),
(15, 'Case Study 01', '2019'),
(15, 'Never Enough', '2023');




INSERT INTO tb_musica(id_musicas, nm_musicas) VALUES
(1, 'Luzes'),
(1, 'Nome nas Ruas'),
(1, 'Só Me Ligar'),
(1, 'Músicas de Amor Nunca Mais'),
(1, 'Amanhecer'),
(1, 'Lugar na Mesa'),
(1, 'Tudo Mudou e Nada Mudou'),
(1, 'Luta e Lucro'),
(1, 'Se Eu Não Lembrar'),
(1, 'Só Eu e Sei'),
(1, 'Só Quero Ver'),
(1, 'Da Madrugada'),
(1, 'Não Adianta Chorar'),
(1, 'Medo de Mim'),
(1, 'Quadros'),
(1, 'Sigo na Sombra'),
(1, 'Caminhos'),
(1, 'Visão Ampla'),
(1, 'O Que Sobra Disso Tudo'),
(2, 'Crime'),
(2, 'EVILJ0RDAN'),
(2, 'SPICY'),
(2, 'COBRA'),
(2, 'KETAMINE'),
(2, 'Rockstar Made'),
(2, 'Go2DamMoon'),
(2, 'New Tank'),
(2, 'Sky'),
(2, 'R.I.P'),
(2, 'Shoota'),
(2, 'Old Money'),
(2, 'Right Now'),
(2, 'Home'),
(3, 'CAROUSEL'),
(3, 'SICKO MODE'),
(3, '5% TINT'),
(3, 'BUTTERFLY EFFECT'),
(3, 'Yosemite'),
(3, 'Pornography'),
(3, '90210'),
(3, 'Wasted'),
(3, 'Pray 4 Love'),
(3, '3500'),
(3, 'HIGHEST IN THE ROOM'),
(3, 'GANG GANG'),
(3, 'OUT WEST'),
(3, 'INTRO'),
(3, 'WHAT TO DO?'),
(4, 'vênus'),
(4, 'jupiter'),
(4, 'plutão'),
(4, 'terra'),
(4, 'saturno'),
(4, 'dia nublado'),
(4, 'sem familia'),
(4, 'dias imortais'),
(4, 'amizade pokemon'),
(4, 'lenda viva'),
(4, 'it a coisa'),
(4, 'palhaçada'),
(4, 'larica'),
(4, 'sinceridade'),
(4, 'sativa'),
(5, 'toretto'),
(5, 'deadpool'),
(5, 'bane'),
(5, 'kratos'),
(5, 'nemesis'),
(5, 'laços'),
(5, 'kaguya'),
(5, 'rinnegan'),
(5, 'shippuden'),
(5, 'katon'),
(5, 'rap dos hokages'),
(5, 'rap do zoro'),
(5, 'rap do itachi'),
(5, 'rap da akatsuki'),
(5, 'rap dos coringas'),
(6, 'bastard x barcha'),
(6, 'ego morto'),
(6, 'absoluto'),
(6, 'morto rico'),
(6, 'rei absoluto'),
(6, 'mirai gohan'),
(6, 'evolucão'),
(6, 'ego superior'),
(6, 'bardock'),
(6, 'goku black'),
(6, 'fim da linha'),
(6, 'sucumba'),
(6, 'aposta alta'),
(6, 'hades'),
(6, 'azul'),
(7, 'Big Boss'),
(7, 'Isso Aqui Vai Virar Zona'),
(7, 'Bonde dos Milionários'),
(7, 'Ta Rico Os Menino Do Gueto'),
(7, 'Intelectual'),
(7, 'Tipo Aladin'),
(7, 'Diz Ai Qual é o Plano?'),
(7, 'Só Mais Um Copo'),
(7, 'Deus,Por Favor'),
(7, 'Olá, Moça'),
(7, 'Goodnight Menina 3'),
(7, 'Goodnight Menina 2'),
(7, 'Migo ou Vida?'),
(7, '4M Paris'),
(7, 'Tá Facin'),
(7, '400K'),
(8, 'Hiperfoco'),
(8, 'Ausência'),
(8, 'Artista Genêrico'),
(8, 'Taylor'),
(8, 'Belieber'),
(8, 'Movimento'),
(8, 'Perdendo a Linha'),
(8, 'Terapia'),
(8, 'VGH Intro'),
(8, 'Dinheiro e Fama'),
(8, 'Rolex'),
(8, 'Só Balão'),
(8, 'Recomeço'),
(9, 'Just Dance'),
(9, 'Poker Face'),
(9, 'Paparazzi'),
(9, 'LoveGame'),
(9, 'Beautiful Dirty Rich'),
(9, 'Born This Way'),
(9, 'Judas'),
(9, 'Edge of Glory'),
(9, 'Marry the Night'),
(9, 'Hair'),
(9, 'Stupid Love'),
(9, 'Rain On Me'),
(9, '911'),
(9, 'Free Woman'),
(9, 'Replay'),
(10, 'Hoje'),
(10, 'Sem Querer'),
(10, 'Fala Mal de Mim'),
(10, 'Garota Recalcada'),
(10, '24 Horas por Dia'),
(10, 'Sou Eu'),
(10, 'Cheguei'),
(10, 'Tipo Crazy'),
(10, 'Bom'),
(10, 'Já É Tarde'),
(10, 'Numanice'),
(10, 'Amor Difícil'),
(10, 'Faz Gostoso'),
(10, 'Verdinha'),
(10, 'Rainha da Favela'),
(11, 'Show das Poderosas'),
(11, 'Meiga e Abusada'),
(11, 'Tá na Mira'),
(11, 'Menina Má'),
(11, 'Proposta'),
(11, 'Bang'),
(11, 'Essa Mina é Louca'),
(11, 'Cravo e Canela'),
(11, 'Deixa Ele Sofrer'),
(11, 'Pode Chegar'),
(11, 'Envolver'),
(11, 'Boys Don’t Cry'),
(11, 'Girl From Rio'),
(11, 'Faking Love'),
(11, 'Lobby'),
(12, 'Evidências'),
(12, 'Fio de Cabelo'),
(12, 'Fogão de Lenha'),
(12, 'Nuvem de Lágrimas'),
(12, 'Se Deus Me Ouvisse'),
(12, 'Cowboy do Asfalto'),
(12, 'Alô'),
(12, 'Brincar de Ser Feliz'),
(12, 'Página de Amigos'),
(12, 'Sinônimos'),
(12, 'Tom do Sertão'),
(12, 'No Rancho Fundo'),
(12, 'Saudade da Minha Terra'),
(12, 'Galopeira'),
(12, 'Majestade o Sabiá'),
(13, 'shut up'),
(13, '34+35'),
(13, 'just like magic'),
(13, 'six thirty'),
(13, 'off the table'),
(13, 'moonlight'),
(13, 'side to side'),
(13, 'into you'),
(13, 'let me love you'),
(13, 'be alright'),
(13, 'honeymoon avenue'),
(13, 'right there'),
(13, 'lovin it'),
(13, 'piano'),
(13, 'tattooed heart'),
(14, 'Set dos Casados'),
(14, 'Baile de Favela 2.0'),
(14, 'Som do Gueto'),
(14, 'Vida Loka'),
(14, 'Nois Que Voa'),
(14, 'Vai na Fé'),
(14, 'Explosão do Beat'),
(14, 'Original'),
(14, 'Mente Criminosa'),
(14, 'Ritmo do Gueto'),
(14, 'Baile Pesadão'),
(14, 'Grave que Balança'),
(14, 'Senta com Força'),
(14, 'Funk Raiz'),
(14, 'Favela Vive'),
(15, 'Get You'),
(15, 'Best Part'),
(15, 'We Find Love'),
(15, 'Blessed'),
(15, 'Hold Me Down'),
(15, 'Cyanide'),
(15, 'Love Again'),
(15, 'Entropy'),
(15, 'Frontal Lobe Muzik'),
(15, 'Superposition'),
(15, 'Do You Like Me?'),
(15, 'Let Me Go'),
(15, 'Valentina'),
(15, 'Always'),
(15, 'Cool');



